---
title: "Chapter 8"
subtitle: "R for Data Science
author: "Tom Madsen"
format:
  html:
    self-contained: true
---

## 8.2 Reading Data from a file
```{r}
library(tidyverse)
students <- read_csv("data/students.csv")

students

```

### 8.2.1 Practical advice
```{r}
students <- read_csv("data/students.csv", na=c("N/A", ""))

students |>
  rename(
    student_id = `Student ID`,
    full_name = `Full Name`
  )

students |> 
  janitor::clean_names() |>
  mutate(meal_plan = factor(meal_plan),
         age = parse_number(if_else(age == "five", "5", age)))

```

### 3.2.2 Other arguments
```{r}
read_csv(
  "a,b,c
  1,2,3
  4,5,6"
)

read_csv(
  "The first line of metadata
  The second line of metadata
  x,y,z
  1,2,3",
  skip = 2
)

read_csv(
  "# A comment I want to skip
  x,y,z
  1,2,3",
  comment = "#"
)

read_csv(
  "1,2,3
  4,5,6",
  col_names = FALSE
)

read_csv(
  "1,2,3
  4,5,6",
  col_names = c("x", "y", "z")
)

```

## 8.4 Reading data from multiple files
```{r}
sales_files <- c("data/01-sales.csv","data/02-sales.csv","data/03-sales.csv")
read_csv(sales_files, id="file")

sales_files <- list.files("data", pattern = "sales\\.csv$", full.names = TRUE)
sales_files
```

## Writing to a file
```{r}
students <- read_csv("data/students.csv") |>
  janitor::clean_names() |>
  mutate(meal_plan = factor(meal_plan))
students

write_csv(students, "data/students-2.csv")

read_csv("data/students-2.csv")

write_rds(students, "data/students.rds")

read_rds("data/students.rds")

library(arrow)

write_parquet(students, "data/students.parquet")

read_parquet("data/students.parquet")

```













