---
title: "R4DS"
subtitle: "Chapter 2"
format: html
---

## Link to the online version of the book:
[R for Data Science 2nd Edition](https://r4ds.hadley.nz/)

```{r}
library(tidyverse)
library(palmerpenguins)
library(ggthemes)
```

```{r}
ggplot(
    data=penguins,
    mapping = aes(x=flipper_length_mm, y=body_mass_g)
    ) +
    geom_point(mapping=aes(color=species, shape=species)) +
    geom_smooth(method="lm") +
    labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)", y="Body mass (g)",
        color="Species", shape="Species"
    ) +
    scale_color_colorblind()
```

```{r}
penguins |>
ggplot(aes(x=flipper_length_mm, y=body_mass_g)) +
geom_point()
```

```{r}
# 2.4.1 A categorical variable
ggplot(penguins, aes(x=species)) +
geom_bar()
```

```{r}
ggplot(penguins, aes(x=fct_infreq(species))) +
geom_bar()
```

```{r}
ggplot(penguins, aes(x=body_mass_g)) + 
geom_histogram(binwidth = 20)
ggplot(penguins, aes(x=body_mass_g)) + 
geom_histogram(binwidth = 2000)
```

```{r}
ggplot(penguins, aes(x=body_mass_g)) +
geom_density()
```

```{r}
# 2.5.1 boxplot
ggplot(penguins, aes(x=species, y=body_mass_g)) +
    geom_boxplot()
```

```{r}
ggplot(penguins, aes(x=body_mass_g, color=species, fill=species)) +
    geom_density(alpha=0.5)
```

```{r}
ggplot(penguins, aes(x=island, fill=species)) +
    geom_bar()
```
```{r}
ggplot(penguins, aes(x=island, fill=species)) +
    geom_bar(position="fill")
```

```{r}
# 2.5.4 Three or more variables 
ggplot(penguins, aes(x=flipper_length_mm, y=body_mass_g)) +
    geom_point(aes(color=species, shape=island))
```

```{r}
ggplot(penguins, aes(x=flipper_length_mm, y=body_mass_g)) +
    geom_point(aes(color=species, shape=species)) +
    facet_wrap(~island)
ggsave(filename = "penguin-plot.pdf")
```